// Contenido del documento de requerimientos de VetPet Connect.
// Todo lo que aparece aquí está redactado desde el pedido de la empresa,
// no desde la solución construida.

const RF = [
  {
    id: 'RF-01', nombre: 'Acceso diferenciado por perfil',
    origen: 'Gerencia General', prioridad: 'Debe tener',
    desc: 'El sistema debe pedir correo y contraseña antes de mostrar cualquier dato de la empresa, de un cliente o de una mascota. Cada persona entra con un solo perfil, y el perfil decide lo que ve: el Cliente solo su información y la de sus mascotas, el Veterinario la agenda y las historias clínicas, y el Administrador el catálogo, el inventario y los pedidos. La gerencia no acepta cuentas que puedan cambiar de perfil por su cuenta ni usuarios con dos perfiles a la vez.',
    crit: 'Un Cliente que intente abrir una pantalla del Veterinario o del Administrador recibe un rechazo, aunque escriba la dirección a mano en el navegador.',
    reglas: 'RN-01',
  },
  {
    id: 'RF-02', nombre: 'Registro autónomo del cliente',
    origen: 'Gerencia General, atención al cliente', prioridad: 'Debe tener',
    desc: 'El dueño de mascota debe poder crear su cuenta solo, desde el celular y a cualquier hora, sin llamar por teléfono ni acercarse al local. El correo electrónico es lo que identifica a la cuenta. La empresa exige además que la contraseña quede guardada de forma que nadie, ni el propio Administrador, pueda leerla.',
    crit: 'Un segundo registro con un correo ya usado se rechaza con un mensaje entendible y no crea la cuenta. En ninguna pantalla ni reporte se puede leer la contraseña de un cliente.',
    reglas: 'RN-02, RN-03',
  },
  {
    id: 'RF-03', nombre: 'Catálogo de productos en línea',
    origen: 'Encargada de tienda', prioridad: 'Debe tener',
    desc: 'El catálogo completo debe verse en línea con la categoría (alimento, accesorio, medicamento de venta libre y arena), la presentación, el precio en soles y si hay existencias. El cliente debe poder filtrar por categoría y buscar por nombre. Los productos que la empresa da de baja no deben seguir apareciendo.',
    crit: 'El filtro de una categoría devuelve solo productos de esa categoría, con el precio vigente. Un producto desactivado por el Administrador deja de aparecer en el catálogo.',
    reglas: 'RN-05, RN-06',
  },
  {
    id: 'RF-04', nombre: 'Carrito de compras',
    origen: 'Cliente piloto, encargada de tienda', prioridad: 'Debe tener',
    desc: 'El cliente debe poder reunir varios productos, cambiar la cantidad, retirar lo que ya no quiere y ver el subtotal de cada línea y el total antes de comprometerse. Si cierra la página y vuelve más tarde, su carrito debe seguir ahí. Un mismo producto no debe aparecer dos veces en la lista: la cantidad se suma.',
    crit: 'Agregar dos veces el mismo producto deja una sola línea con la cantidad sumada. El total mostrado coincide siempre con la suma de las líneas. Una cantidad de cero o negativa se rechaza.',
    reglas: 'RN-09, RN-10, RN-11',
  },
  {
    id: 'RF-05', nombre: 'Confirmación del pedido con descuento de inventario',
    origen: 'Gerencia General', prioridad: 'Debe tener',
    desc: 'Al confirmar la compra, el sistema debe descontar en ese mismo momento las unidades del inventario y dejar registrado el pedido con el precio que el cliente vio en pantalla. La gerencia exige que el pedido sea todo o nada: si falta stock de un solo producto no se emite nada, y se le informa al cliente qué producto falta y cuántas unidades quedan disponibles.',
    crit: 'Con dos clientes comprando al mismo tiempo la última unidad, uno obtiene el pedido y el otro recibe el aviso de falta de stock. El inventario nunca queda en negativo y no se emiten pedidos incompletos.',
    reglas: 'RN-07, RN-11, RN-12, RN-14',
  },
  {
    id: 'RF-06', nombre: 'Pago en línea con tarjeta',
    origen: 'Gerencia General', prioridad: 'Debe tener',
    desc: 'La empresa necesita cobrar en el momento de la compra, con tarjeta de crédito o débito, a través de una pasarela de pagos peruana (Culqi, Niubiz o equivalente). VetPet Surco no quiere guardar números de tarjeta en su sistema ni hacerse responsable de ellos. Un pedido solo puede darse por pagado si la pasarela aprueba el cobro; si lo rechaza, el pedido queda pendiente y el cliente puede volver a intentarlo.',
    crit: 'Un cobro rechazado deja el pedido en estado pendiente y queda registrado el intento con su motivo. Ninguna pantalla, registro ni reporte guarda el número completo de la tarjeta.',
    reglas: 'RN-13, RN-21',
  },
  {
    id: 'RF-07', nombre: 'Seguimiento del estado del pedido',
    origen: 'Atención al cliente', prioridad: 'Debe tener',
    desc: 'El cliente debe poder ver en qué punto va su pedido sin llamar al local: pendiente, pagado, enviado, entregado o anulado. El Administrador es quien hace avanzar el estado, y el sistema no debe permitir saltarse pasos ni retroceder, porque hoy eso genera reclamos que nadie puede aclarar.',
    crit: 'Intentar marcar como entregado un pedido que todavía está pendiente se rechaza. El cliente ve el estado actualizado en su historial de pedidos.',
    reglas: 'RN-13',
  },
  {
    id: 'RF-08', nombre: 'Suscripción mensual por mascota',
    origen: 'Gerencia General', prioridad: 'Debe tener',
    desc: 'El cliente debe poder contratar un plan mensual para una mascota y un producto concreto, eligiendo entre tres niveles que se diferencian en cuántas unidades entran en cada despacho. Debe poder pausar el plan cuando se va de viaje y cancelarlo cuando quiera, desde su cuenta, sin llamar ni pedir permiso. La empresa tampoco quiere cobrar dos veces lo mismo: una mascota no puede tener dos planes vigentes del mismo producto.',
    crit: 'Pausar un plan detiene los despachos siguientes y reactivarlo los reanuda. Un segundo plan vigente del mismo producto para la misma mascota se rechaza.',
    reglas: 'RN-15, RN-16, RN-22',
  },
  {
    id: 'RF-09', nombre: 'Despacho recurrente automático',
    origen: 'Gerencia General', prioridad: 'Debe tener',
    desc: 'Llegada la fecha del plan, el sistema debe emitir el pedido por su cuenta, sin que el cliente lo pida ni el personal lo recuerde: ese es el ingreso estable que la empresa busca. El pedido debe quedar identificado como despacho de suscripción para poder separarlo de la venta directa en los reportes. Si ese día no hay stock, el despacho se posterga y se recupera en cuanto haya reposición; no se emite un pedido incompleto ni se pierde el mes.',
    crit: 'Con el plan activo y stock suficiente, en la fecha programada aparece el pedido marcado como suscripción y la próxima fecha avanza. Sin stock, no se emite nada y la fecha no avanza.',
    reglas: 'RN-12, RN-14, RN-15, RN-16',
  },
  {
    id: 'RF-10', nombre: 'Registro de las mascotas del cliente',
    origen: 'Médico veterinario jefe', prioridad: 'Debe tener',
    desc: 'Cada cliente debe poder registrar sus mascotas con nombre, especie, raza, fecha de nacimiento y peso, y mantenerlas actualizadas. Toda mascota pertenece a un cliente registrado: el sistema no debe permitir mascotas sin dueño, y ningún cliente debe poder ver ni agendar para mascotas de otro.',
    crit: 'En todos los formularios del sistema, un cliente solo ve y selecciona sus propias mascotas.',
    reglas: 'RN-04',
  },
  {
    id: 'RF-11', nombre: 'Agenda de citas sin cruce de horarios',
    origen: 'Médicos veterinarios', prioridad: 'Debe tener',
    desc: 'El cliente debe poder reservar una cita eligiendo el servicio (consulta, vacunación, desparasitación o grooming), el profesional, la fecha y la hora, viendo únicamente los horarios realmente libres. Este es el problema más caro que tiene hoy la empresa: dos citas asignadas al mismo veterinario a la misma hora, porque la agenda se coordina por teléfono y por WhatsApp.',
    crit: 'Si dos clientes reservan al mismo tiempo el mismo veterinario a la misma hora, solo una reserva queda registrada y la otra recibe un aviso claro.',
    reglas: 'RN-04, RN-17',
  },
  {
    id: 'RF-12', nombre: 'Cierre de la cita con desenlace',
    origen: 'Gerencia General', prioridad: 'Debe tener',
    desc: 'Toda cita debe terminar con un desenlace explícito: atendida, cancelada o el cliente no asistió. La empresa quiere medir la inasistencia para saber si las alertas están funcionando, y para eso no pueden quedar citas abiertas del mes pasado.',
    crit: 'El veterinario cierra cada cita de su agenda con uno de los tres desenlaces, y el indicador de inasistencia se calcula sobre ellos.',
    reglas: 'RN-18',
  },
  {
    id: 'RF-13', nombre: 'Historia clínica digital',
    origen: 'Médicos veterinarios', prioridad: 'Debe tener',
    desc: 'El sistema debe reemplazar las fichas de cartón archivadas en el local. En cada atención el veterinario registra el diagnóstico, el tratamiento, la vacuna aplicada y la fecha del próximo control. El historial completo de la mascota debe poder consultarse desde cualquier lugar, y el dueño debe poder verlo también.',
    crit: 'Cada atención genera un único registro clínico ligado a esa cita, y el historial de la mascota muestra las atenciones en orden de fecha.',
    reglas: 'RN-19',
  },
  {
    id: 'RF-14', nombre: 'Alertas de vacunación y desparasitación',
    origen: 'Gerencia General, médicos veterinarios', prioridad: 'Debe tener',
    desc: 'El sistema debe avisar al dueño quince días antes de la próxima vacunación o desparasitación de su mascota, sin que nadie del local tenga que revisar la agenda a mano. Es la medida con la que la empresa espera reducir en 40% las inasistencias a los controles.',
    crit: 'Una mascota cuyo próximo control cae dentro de los próximos quince días aparece en la lista de recordatorios, con los días que faltan y el correo del dueño.',
    reglas: 'RN-20',
  },
  {
    id: 'RF-15', nombre: 'Control de inventario con alerta de reposición',
    origen: 'Encargada de tienda', prioridad: 'Debe tener',
    desc: 'Cada producto debe tener un punto de reorden definido por la empresa. El sistema debe mostrar con un semáforo qué productos están por agotarse y avisar al Administrador después de cada venta, para que la reposición deje de depender del cuaderno y de la memoria del personal.',
    crit: 'Cuando el stock llega al punto de reorden o baja de él, el producto aparece en rojo en el panel del Administrador y en la alerta posterior a la venta.',
    reglas: 'RN-07, RN-08',
  },
  {
    id: 'RF-16', nombre: 'Mantenimiento del catálogo y de los pedidos',
    origen: 'Administración', prioridad: 'Debe tener',
    desc: 'El Administrador debe poder dar de alta, editar y dar de baja productos, precios, stock y puntos de reorden, y gestionar los pedidos, sin pedir ayuda a un programador cada vez. Cada producto se identifica con un código interno que no se repite, y el sistema no debe aceptar un precio de cero o negativo.',
    crit: 'El Administrador crea un producto y este aparece de inmediato en el catálogo. Un código repetido o un precio menor o igual a cero se rechazan.',
    reglas: 'RN-05, RN-06',
  },
  {
    id: 'RF-17', nombre: 'Sitio institucional público',
    origen: 'Gerencia General', prioridad: 'Debería tener',
    desc: 'Debe existir una parte pública, sin necesidad de tener cuenta, con la presentación de la empresa, los servicios, los horarios, la ubicación y un formulario de contacto. Hoy los clientes nuevos encuentran a VetPet Surco solo caminando por la avenida, y la empresa quiere que también la encuentren buscando en internet.',
    crit: 'Las páginas institucionales se ven sin iniciar sesión, desde una computadora y desde un celular.',
    reglas: '—',
  },
];

const RNF = [
  ['RNF-01', 'Diseño adaptable al celular', 'La interfaz debe funcionar completa en un teléfono, porque la mayoría de los dueños va a comprar y a reservar desde el celular. No se acepta una versión móvil recortada.', 'Se completa una compra y una reserva de cita en una pantalla de 360 px de ancho, sin desplazamiento horizontal.'],
  ['RNF-02', 'Protección de credenciales y datos personales', 'Las contraseñas deben guardarse cifradas y ser imposibles de recuperar en texto legible. Los datos personales del cliente se tratan conforme a la Ley N.º 29733 de Protección de Datos Personales del Perú.', 'La consulta directa a los datos almacenados no devuelve ninguna contraseña legible.'],
  ['RNF-03', 'Operación simultánea sin sobreventa', 'Varias personas deben poder comprar y reservar al mismo tiempo sin que el sistema venda dos veces la misma unidad ni entregue dos veces el mismo horario.', 'Prueba de dos compras y dos reservas simultáneas sobre el último recurso disponible: una gana, la otra recibe el aviso.'],
  ['RNF-04', 'Tiempo de respuesta', 'El catálogo debe cargar en no más de 3 segundos con una conexión móvil estándar. Un cliente que espera más, se va.', 'Medición del tiempo de carga del catálogo en conexión móvil 4G.'],
  ['RNF-05', 'Disponibilidad fuera del horario del local', 'El sistema debe estar disponible las 24 horas. El sentido de todo el proyecto es capturar al cliente que escribe a las once de la noche, cuando el local está cerrado.', 'La reserva de citas y la compra se completan fuera del horario de atención del local.'],
  ['RNF-06', 'Facilidad de uso del personal', 'El personal de VetPet Surco no tiene formación informática. Cada módulo debe poder aprenderse en una sesión de capacitación de treinta minutos y toda la interfaz debe estar en español.', 'Un colaborador sin entrenamiento previo completa las tareas de su perfil tras una capacitación de 30 minutos.'],
  ['RNF-07', 'Moneda, idioma y horario locales', 'Todos los importes en soles (S/), las fechas en formato dd/mm/aaaa y las horas en el huso horario de Lima. Los textos, en español.', 'Revisión de pantallas y comprobantes.'],
  ['RNF-08', 'Reglas garantizadas por el almacén de datos', 'La gerencia exige que las reglas críticas (stock que no baja de cero, un horario por veterinario, un correo por cuenta) estén garantizadas también en la base de datos y no solo en la pantalla, para que un error de programación futuro no pueda romperlas.', 'Un intento de grabar datos que violen esas reglas, hecho directamente sobre la base, es rechazado por el motor.'],
  ['RNF-09', 'Precio histórico del pedido', 'El precio de un pedido ya emitido no puede cambiar aunque después se actualice la lista de precios. La empresa necesita poder responder un reclamo con el precio que el cliente realmente vio.', 'Cambiar el precio de un producto no altera el total de un pedido emitido antes del cambio.'],
  ['RNF-10', 'Respaldo de la información', 'Copia de seguridad diaria de toda la información, con retención de treinta días. Las historias clínicas son el activo que la empresa no puede volver a reunir si se pierde.', 'Existe una copia diaria verificada y una prueba de restauración documentada.'],
  ['RNF-11', 'Independencia del proveedor', 'El sistema debe poder instalarse en un servidor de hosting estándar o en contenedores, sin quedar amarrado a un único proveedor de nube. La empresa es una MYPE y necesita poder mudarse si el costo sube.', 'El despliegue se reproduce en un segundo entorno siguiendo la documentación entregada.'],
  ['RNF-12', 'Evidencia comprobable del cumplimiento', 'VetPet Surco exige poder comprobar, antes de cada entrega, que las reglas de negocio se siguen cumpliendo, mediante pruebas que cualquiera del equipo pueda volver a ejecutar.', 'Se entrega un juego de pruebas reproducible que cubre las 22 reglas del capítulo 8.'],
];

const RN = [
  ['RN-01', 'Cada persona entra con un solo perfil. Nadie es cliente y veterinario a la vez.', 'RF-01'],
  ['RN-02', 'Un correo electrónico pertenece a una sola cuenta.', 'RF-02'],
  ['RN-03', 'Nadie de la empresa, ni el Administrador, puede leer la contraseña de un cliente.', 'RF-02'],
  ['RN-04', 'Toda mascota tiene un dueño registrado. No hay mascotas sin cliente.', 'RF-10, RF-11'],
  ['RN-05', 'Cada producto tiene un código interno propio que no se repite.', 'RF-16'],
  ['RN-06', 'Ningún producto se vende en cero ni en precio negativo.', 'RF-16'],
  ['RN-07', 'El inventario nunca queda en negativo.', 'RF-05, RF-15'],
  ['RN-08', 'Cuando el stock llega al punto de reorden hay que reponer, y el sistema debe avisarlo.', 'RF-15'],
  ['RN-09', 'Un producto aparece una sola vez en un pedido; si se repite, se suma la cantidad.', 'RF-04'],
  ['RN-10', 'No se compran cantidades de cero o menos.', 'RF-04'],
  ['RN-11', 'El precio de un pedido ya emitido no cambia.', 'RF-04, RF-05'],
  ['RN-12', 'Si no hay stock completo no hay pedido: preferimos no vender antes que prometer lo que no tenemos.', 'RF-05, RF-09'],
  ['RN-13', 'El pedido avanza en orden: pendiente, pagado, enviado, entregado. Anular es la única salida.', 'RF-07'],
  ['RN-14', 'La venta directa y el despacho por suscripción se distinguen siempre.', 'RF-05, RF-09'],
  ['RN-15', 'El cliente pausa o cancela su plan cuando quiera, sin llamar al local.', 'RF-08'],
  ['RN-16', 'Cada plan tiene una frecuencia fija de 30 días y una próxima fecha de despacho conocida.', 'RF-08, RF-09'],
  ['RN-17', 'Un veterinario no atiende dos citas a la misma hora.', 'RF-11'],
  ['RN-18', 'Toda cita se cierra con un desenlace: atendida, cancelada o no asistió.', 'RF-12'],
  ['RN-19', 'Cada atención genera un único registro clínico.', 'RF-13'],
  ['RN-20', 'Se avisa al dueño quince días antes del próximo control.', 'RF-14'],
  ['RN-21', 'Un pedido pasa a pagado solo si la pasarela aprueba el cobro.', 'RF-06'],
  ['RN-22', 'Una mascota no puede tener dos planes vigentes del mismo producto.', 'RF-08'],
];

module.exports = { RF, RNF, RN };
